Feature/ignore interface regex
tomarrell/wrapcheck pull request #25
Opened 2022-03-21 17:34 UTC by guillaumeio

Hi Tom! 
This PR intends to bring flexibility to wrapcheck with errors returned from Interfaces  types:

Allows ignore unwrapped errors returned from interfaces. Define regexps rules to explicitly ignore underlying interfaces with mandated methods to ignore, according to the interface names. Even though this could technically be done with thought-out ignoreSigRegexps, this allows to explicitly and cleanly define rules in the config to define sub cases of IsInterface.

PS: fixed typos

2022-03-22 10:39 UTC, tomarrell requested changes
Hey Guillaume!

Thanks a lot for the PR, much appreciated. I've left a few minor comments.

Cheers for adding the test as well.

2022-03-22 10:39 UTC, tomarrell commented on wrapcheck/testdata/config_ignoreInterfaceRegexps/main.go
> +		return err // errorer interface ignored
Just a minor suggestion
```suggestion
		return err // errorer interface ignored as per `ignoreInterfaceRegexps`
```

2022-03-22 10:39 UTC, tomarrell commented on README.md
> +# An array of strings which specify regular expressions of interface names.
Maybe we could make this a little more succinct. I liked the description on the config struct more, maybe we could use that here.

```
// IgnoreInterfaceRegexps defines a list of regular expressions which, if matched
// to a underlying interface name, will ignore unwrapped errors returned from a
// function whose call is defined on the given interface.
```

2022-03-22 10:39 UTC, tomarrell commented on wrapcheck/wrapcheck.go
> +	ignoreInterfaceRegexps, err2 := compileRegexps(cfg.IgnoreInterfaceRegexps)
I was thinking, I've actually made some similar changes, still local for now, in order to precompile the globs. Could we maybe update this to something along the lines of:

```go
var (
	ignoreSigRegexp    []*regexp.Regexp
	ignorePackageGlobs []glob.Glob
	err                error
)

ignoreSigRegexp, err = compileRegexps(cfg.IgnoreSigRegexps)
if err != nil {
	ignorePackageGlobs, err = compileGlobs(cfg.IgnorePackageGlobs)
}
```

I will likely refactor this anyway in an upcoming PR, but for now I'd prefer not to have multiple error checks in the returned func below.

2022-03-22 10:39 UTC, tomarrell commented on wrapcheck/wrapcheck.go
> +		if containsMatch(regexpsInter, types.TypeString(pass.TypesInfo.TypeOf(sel.X), func(p *types.Package) string { return p.Name() })) {
Could we maybe pull this out of a single line? It's a little dense to read as it is and could be simpler.

2022-03-22 18:19 UTC, guillaumeio commented
Thanks for the review!
Tried my go at refactoring. Please let me know if this is what you intended  :)

2022-03-22 22:11 UTC, tomarrell approved these changes
Nice job! Thanks a lot for that. Didn't actually intend for you to also add the globs, but I appreciate you doing it!

Will merge this now and probably cut a new release tomorrow. 

Thanks again for the contribution!

2022-03-23 00:24 UTC, merged

2022-03-23 14:32 UTC, guillaumeio commented
Thanks for the kind words!
Would love a new release :)
Cheers Tom!